name: Cypress Docker Compose Workflow

on:
  schedule:
    - cron: "*/1 * * * *"  # กำหนดให้ทำงานทุกๆ 1 นาที
  push:
    branches:
      - main  # จะทำงานเมื่อมีการ push ไปที่ branch main
  pull_request:
    branches:
      - main

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017
      minio:
        image: minio/minio
        options: --entrypoint "sh -c 'minio server /data'"
        ports:
          - 9000:9000
        env:
          MINIO_ACCESS_KEY: "sorry-cypress"
          MINIO_SECRET_KEY: "this-is-a-secret"
      director:
        image: agoldis/sorry-cypress-director
        env:
          MONGODB_URI: "mongodb://mongo:27017/sorry-cypress"
          S3_ACCESS_KEY_ID: "sorry-cypress"
          S3_SECRET_ACCESS_KEY: "this-is-a-secret"
          S3_ENDPOINT: "http://minio:9000"
          S3_BUCKET_NAME: "sorry-cypress"
          S3_NO_PATH_STYLE: "true"
      sorry-cypress-dashboard:
        image: agoldis/sorry-cypress-dashboard
        ports:
          - 8080:8080
        env:
          MONGODB_URI: "mongodb://mongo:27017/sorry-cypress"
          S3_ACCESS_KEY_ID: "sorry-cypress"
          S3_SECRET_ACCESS_KEY: "this-is-a-secret"
          S3_ENDPOINT: "http://minio:9000"
          S3_BUCKET_NAME: "sorry-cypress"
          S3_NO_PATH_STYLE: "true"
          PORT: "8080"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d  # ใช้ Docker Compose ในการรันคอนเทนเนอร์ใน Pipeline

      - name: Wait for services to be ready
        run: |
          sleep 30  # รอเวลาบางส่วนให้คอนเทนเนอร์ต่างๆ สามารถเริ่มทำงานได้

      - name: Run Cypress tests
        run: |
          docker-compose exec cypress cypress run --record --key b0c24596-9777-4425-b934-bdef2019e480

      - name: Stop Docker Compose services
        run: |
          docker-compose down
